### ISSUE TITLE
In-game TASing

### ISSUE THREAD

**Issue by Eddio0141** [Eddio0141/UniTAS#237]
after some people tried using this tool, they didn't get too far mostly with lua scripting being too hard and tedious to do

so that means I have to do in-game TASing as most tools do!!!

# Idea
- in-game TASing will write to the lua script
- for advanced users, they can write lua functions which will be used for automation (which is going to be a coroutine), which can be accessed with in-game TASing
  - this should be able to be written in the lua side or with some in-game window
  - identify either by name of the function OR by adding to a predefined list

# TODOs
- [ ] frame advancing in-game
- [ ] in-game TASing write to movie lua script
- [ ] in-game TASing GUI
