### ISSUE TITLE
Check if unity project settings needs to be restored

### ISSUE THREAD

**Issue by Eddio0141** [Eddio0141/UniTAS#249]
Some settings like `QualitySettings.vSyncCount` and `Application.targetFrameRate` might need to be stored and restored on restart

# TODOs
- [ ] Check if project settings need to be stored for restoration
  - If not, close issue and move on
- [ ] Implementation restoration mechanic
  - [ ] Probably merge the existing "reset events" and make it better with this combination
- [ ] Might also need to exclude unity almost entirely from resetting static values, as those restore to default
- [ ] Determine what needs to be restored
