### ISSUE TITLE
ScriptableObject objects not affected by soft restart

### ISSUE THREAD

**Issue by Eddio0141** [Eddio0141/UniTAS#267]
Currently its jank and barely works
When TAS playback ends, you can't control the game anymore
ULTRAKILL spams warnings / errors for the new input system and can't control

**Comment by Eddio0141** [comment]
Seems like its uGUI's new input system module breaks on soft restart

**Comment by Eddio0141** [comment]
I think I figured it out
In unity, you can bind some object to a serializable field (which works as a reference for most types i think other than for primitives)
When the binded object is reference type and is updated in any way like doing `component_field.value++`, that value is preserved through soft restart, which is really bad
`InputSystemUIInputModule` uses `InputActionReference` which is assigned through a serializable field in the editor, and the state of them doesn't get reset on soft restart

# TODOs
- [ ] test if soft restart work on serializable field assigning
  - [ ] reference type
  - [ ] value type
- [ ] test where is the reference type stored in (try finding with Resources class)
- [ ] reset the referencing object on soft restart
  - [ ] if even possible, re-instantiate the referencing object to reset it
    - [ ] otherwise, work on saving the state for some objects on start up (related to #21)

**Comment by Eddio0141** [comment]
I successfully replicated the bug with a test object deriving from `ScriptableObject` and its value persists after soft restart

**Comment by Eddio0141** [comment]
Subject: [PATCH] Changes
---
Index: UniTAS/Patcher/Implementations/UnityFix/SaveScriptableObjectStates.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/UniTAS/Patcher/Implementations/UnityFix/SaveScriptableObjectStates.cs b/UniTAS/Patcher/Implementations/UnityFix/SaveScriptableObjectStates.cs
--- a/UniTAS/Patcher/Implementations/UnityFix/SaveScriptableObjectStates.cs	
+++ b/UniTAS/Patcher/Implementations/UnityFix/SaveScriptableObjectStates.cs	
@@ -1,3 +1,4 @@
+using System;
 using System.Collections.Generic;
 using System.Linq;
 using System.Reflection;
@@ -10,10 +11,11 @@
 using UniTAS.Patcher.Services.Trackers.UpdateTrackInfo;
 using UniTAS.Patcher.Utils;
 using UnityEngine;
+using Object = UnityEngine.Object;
 
 namespace UniTAS.Patcher.Implementations.UnityFix;
 
-[Singleton]
+// [Singleton]
 public partial class SaveScriptableObjectStates : INewScriptableObjectTracker, IOnAwakeUnconditional, IOnPreGameRestart
 {
     private readonly List<StoredState> _storedStates = new();
@@ -23,15 +25,27 @@
     private readonly ITryFreeMalloc _freeMalloc;
 
     private readonly Assembly[] _ignoreAssemblies;
+    private readonly Type[] _ignoreTypes;
 
     public SaveScriptableObjectStates(ILogger logger, ITryFreeMalloc freeMalloc)
     {
         _logger = logger;
         _freeMalloc = freeMalloc;
 
+        _ignoreTypes = new[]
+        {
+            // TODO why does this break the hud?
+            AccessTools.TypeByName("Unity.VisualScripting.VariablesAsset"),
+
+            // TODO do i remove t his
+        }.Where(x => x != null).ToArray();
+
         _ignoreAssemblies = new[]
         {
-            AccessTools.TypeByName("TMPro.TMP_FontAsset")
+            // TODO not sure if i should do this
+            // TODO why does this break the hud?
+            AccessTools.TypeByName("TMPro.TMP_FontAsset"),
+            AccessTools.TypeByName("UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset")
         }.Where(x => x != null).Select(x => x.Assembly).ToArray();
     }
 
@@ -50,12 +64,15 @@
     {
         _logger.LogDebug("Saving all ScriptableObject states");
 
+        // filter types to save
         var allScriptableObjects = ResourcesUtils.FindObjectsOfTypeAll<ScriptableObject>()
-            .Where(x => _ignoreAssemblies.All(a => !Equals(a, x.GetType().Assembly))).ToArray();
+            .Where(x => _ignoreAssemblies.All(a => !Equals(a, x.GetType().Assembly)) &&
+                        _ignoreTypes.All(a => a != x.GetType())).ToArray();
         _logger.LogDebug($"Found {allScriptableObjects.Length} ScriptableObjects");
 
         foreach (var obj in allScriptableObjects)
         {
+            _logger.LogDebug($"Saving ScriptableObject {obj.name} with type {obj.GetType().FullName}");
             Save(obj);
         }
     }
Index: UniTAS/Patcher/Implementations/UnityFix/SaveScriptableObjectStates.Types.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/UniTAS/Patcher/Implementations/UnityFix/SaveScriptableObjectStates.Types.cs b/UniTAS/Patcher/Implementations/UnityFix/SaveScriptableObjectStates.Types.cs
--- a/UniTAS/Patcher/Implementations/UnityFix/SaveScriptableObjectStates.Types.cs	
+++ b/UniTAS/Patcher/Implementations/UnityFix/SaveScriptableObjectStates.Types.cs	
@@ -4,7 +4,6 @@
 using System.Reflection;
 using HarmonyLib;
 using UniTAS.Patcher.Extensions;
-using UniTAS.Patcher.Models.Utils;
 using UniTAS.Patcher.Services;
 using UniTAS.Patcher.Services.Logging;
 using UniTAS.Patcher.Utils;
@@ -20,38 +19,26 @@
         public readonly ScriptableObject ScriptableObject;
 
         private readonly FieldData[] _savedFields;
-        private readonly FieldInfo[] _resetFields;
 
         private readonly ILogger _logger;
-        private readonly ITryFreeMalloc _freeMalloc;
 
         public StoredState(ScriptableObject scriptableObject, ILogger logger, ITryFreeMalloc freeMalloc)
         {
             ScriptableObject = scriptableObject;
             _logger = logger;
-            _freeMalloc = freeMalloc;
 
             // save
             var fields = scriptableObject.GetType().GetFieldsRecursive(AccessTools.all)
                 .Where(x => !x.IsStatic && !x.IsLiteral && x.DeclaringType != typeof(Object));
 
-            var resetFields = new List<FieldInfo>();
             var savedFields = new List<FieldData>();
 
             foreach (var field in fields)
             {
-                if (field.IsFieldUnitySerializable())
-                {
-                    savedFields.Add(new(field, scriptableObject, logger, freeMalloc));
-                    continue;
-                }
-
-                StaticLogger.Trace("Field is not unity serializable, resetting on load");
-                resetFields.Add(field);
+                savedFields.Add(new(field, scriptableObject, logger, freeMalloc));
             }
 
             _savedFields = savedFields.ToArray();
-            _resetFields = resetFields.ToArray();
         }
 
         public void Load()
@@ -62,23 +49,21 @@
                 return;
             }
 
+            _logger.LogDebug($"ScriptableObject before: {DebugHelp.PrintClass(ScriptableObject)}");
+
             foreach (var savedField in _savedFields)
             {
                 savedField.Load();
             }
 
-            foreach (var resetField in _resetFields)
-            {
-                _freeMalloc?.TryFree(ScriptableObject, resetField);
-                resetField.SetValue(ScriptableObject, null);
-            }
+            _logger.LogDebug($"ScriptableObject after: {DebugHelp.PrintClass(ScriptableObject)}");
         }
     }
 
     private readonly struct FieldData
     {
         private readonly ScriptableObject _instance;
-        private readonly Either<Object, object> _value;
+        private readonly object _value;
         private readonly FieldInfo _saveField;
 
         private readonly ITryFreeMalloc _freeMalloc;
@@ -111,7 +96,7 @@
             _freeMalloc?.TryFree(_instance, _saveField);
 
             // additional one to make it not use the stored value
-            var value = DeepCopy.MakeDeepCopy(_value.IsLeft ? _value.Left : _value.Right);
+            var value = DeepCopy.MakeDeepCopy(_value);
             _saveField.SetValue(_instance, value);
         }
     }
Index: UniTAS/Patcher/Patches/Harmony/InputSystemTrackerPatch.cs
===================================================================
diff --git a/UniTAS/Patcher/Patches/Harmony/InputSystemTrackerPatch.cs b/UniTAS/Patcher/Patches/Harmony/InputSystemTrackerPatch.cs
new file mode 100644
--- /dev/null	
+++ b/UniTAS/Patcher/Patches/Harmony/InputSystemTrackerPatch.cs	
@@ -0,0 +1,52 @@
+using System;
+using System.Diagnostics;
+using System.Linq;
+using System.Reflection;
+using HarmonyLib;
+using UniTAS.Patcher.Interfaces.Patches.PatchTypes;
+using UniTAS.Patcher.Services.Trackers.UpdateTrackInfo;
+using UniTAS.Patcher.Utils;
+
+namespace UniTAS.Patcher.Patches.Harmony;
+
+// [RawPatch]
+public class InputSystemTrackerPatch
+{
+    private static readonly INotifyDeviceDiscoveredInvokes NotifyDeviceDiscoveredInvokes =
+        ContainerStarter.Kernel.GetInstance<INotifyDeviceDiscoveredInvokes>();
+
+    [HarmonyPatch]
+    private class NotifyDeviceDiscoveredTracker
+    {
+        private static Exception Cleanup(MethodBase original, Exception ex)
+        {
+            return PatchHelper.CleanupIgnoreFail(original, ex);
+        }
+
+        private static MethodBase TargetMethod()
+        {
+            return AccessTools.Method("UnityEngineInternal.Input.NativeInputSystem:NotifyDeviceDiscovered");
+        }
+
+        private static void Prefix(object[] __args)
+        {
+            // ignore track if UniTAS invoke
+            var frames = new StackTrace().GetFrames();
+            if (frames == null)
+            {
+                NotifyDeviceDiscoveredInvokes.Invoke(__args);
+                return;
+            }
+
+            // ignore this method in stack trace
+            if (frames.Skip(1).Any(f => f.GetMethod().DeclaringType?.Namespace?.StartsWith("UniTAS") is true)) return;
+
+            // TODO remove this logging
+            StaticLogger.Log.LogDebug(
+                $"UnityEngine.InputSystem.InputManager:OnNativeDeviceDiscovered called\n{new StackTrace()}");
+            StaticLogger.Log.LogDebug($"Device ID: {__args[0]}\nDevice Descriptor: {__args[1]}");
+
+            NotifyDeviceDiscoveredInvokes.Invoke(__args);
+        }
+    }
+}
\ No newline at end of file
Index: UniTAS/Patcher/Services/Trackers/UpdateTrackInfo/INotifyDeviceDiscoveredInvokes.cs
===================================================================
diff --git a/UniTAS/Patcher/Services/Trackers/UpdateTrackInfo/INotifyDeviceDiscoveredInvokes.cs b/UniTAS/Patcher/Services/Trackers/UpdateTrackInfo/INotifyDeviceDiscoveredInvokes.cs
new file mode 100644
--- /dev/null	
+++ b/UniTAS/Patcher/Services/Trackers/UpdateTrackInfo/INotifyDeviceDiscoveredInvokes.cs	
@@ -0,0 +1,6 @@
+namespace UniTAS.Patcher.Services.Trackers.UpdateTrackInfo;
+
+public interface INotifyDeviceDiscoveredInvokes
+{
+    void Invoke(object[] args);
+}
\ No newline at end of file
Index: UniTAS/Patcher/Implementations/UnityFix/RecallNotifyDeviceDiscovered.cs
===================================================================
diff --git a/UniTAS/Patcher/Implementations/UnityFix/RecallNotifyDeviceDiscovered.cs b/UniTAS/Patcher/Implementations/UnityFix/RecallNotifyDeviceDiscovered.cs
new file mode 100644
--- /dev/null	
+++ b/UniTAS/Patcher/Implementations/UnityFix/RecallNotifyDeviceDiscovered.cs	
@@ -0,0 +1,51 @@
+using System.Collections.Generic;
+using System.Diagnostics;
+using System.Reflection;
+using HarmonyLib;
+using UniTAS.Patcher.Interfaces.DependencyInjection;
+using UniTAS.Patcher.Services.InputSystemOverride;
+using UniTAS.Patcher.Services.Logging;
+using UniTAS.Patcher.Services.Movie;
+using UniTAS.Patcher.Services.Trackers.UpdateTrackInfo;
+
+namespace UniTAS.Patcher.Implementations.UnityFix;
+
+// [Singleton]
+public class RecallNotifyDeviceDiscovered : INotifyDeviceDiscoveredInvokes
+{
+    private readonly ILogger _logger;
+
+    private readonly List<object[]> _invokes = new();
+
+    private readonly MethodBase _notifyDeviceDiscovered =
+        AccessTools.Method("UnityEngineInternal.Input.NativeInputSystem:NotifyDeviceDiscovered");
+
+    public RecallNotifyDeviceDiscovered(ILogger logger, INewInputSystemExists newInputSystemExists,
+        IMovieRunnerEvents movieRunnerEvents)
+    {
+        if (!newInputSystemExists.HasInputSystem) return;
+        _logger = logger;
+
+        if (_notifyDeviceDiscovered == null)
+        {
+            logger.LogWarning("UnityEngineInternal.Input.NativeInputSystem.NotifyDeviceDiscovered not found");
+            return;
+        }
+
+        movieRunnerEvents.OnMovieEnd += MovieEnd;
+    }
+
+    public void Invoke(object[] args)
+    {
+        _logger.LogDebug($"NotifyDeviceDiscovered invoked: {new StackTrace()}");
+        _invokes.Add(args);
+    }
+
+    private void MovieEnd()
+    {
+        foreach (var invoke in _invokes)
+        {
+            _notifyDeviceDiscovered.Invoke(null, invoke);
+        }
+    }
+}
\ No newline at end of file

**Comment by Eddio0141** [comment]
[changes.txt](https://github.com/Eddio0141/UniTAS/files/13386315/changes.txt)

patch file for current progress for later pr open

**Comment by Eddio0141** [comment]
could actually use the serialized info stored in assets instead
use AssetTools.NET to decode data
this method would be much cleaner to do and much much easier (it should work)

- [ ] find where the data lives
- [ ] attempt to find how to serialize to get actual data
- [ ] what happens with references? check!
- [ ] what happens with non-serializable data? is it default value?
