### ISSUE TITLE
Check property getter for unity API for initial value?

### ISSUE THREAD

**Issue by Eddio0141** [Eddio0141/UniTAS#289]
# Simple idea

For properties that
- Has both getter and setter
- Is calling external code
- Is unity API

We store the getter value on special location for later

And on soft restart
1. Check if the value changed by get
2. Only apply the initial value if not the same value (avoid calling external code as much as possible)

# Problems?
- Don't know if some or most properties should be handled like this
  - Maybe better to simply check for handled extern properties, and check against what UniTAS handles

**Comment by Eddio0141** [comment]
seems like there are many that fits this category, all unhandled by UniTAS
probably best approach is to automatically handle most, while some are excluded manually

# TODOs
- [ ] handle properties
  - make sure its done through mono.cecil apis (i think) since checking for extern throws an exception
  - handle `get` `set` that is `extern`
  - [ ] make sure i go through all the properties and make a list of known properties
  - [ ] if property isn't known, warn and still handle it
- [ ] test across games and exclude / troubleshoot any troubled property
